import requests

def download_html(link, filename):
    response = requests.get(link)
    if response.status_code == 200:
        with open(filename, 'w', encoding="utf-8") as file:
            file.write(response.text)
        print(f"Downloaded {link} as {filename}")
    else:
        print(f"Failed to download {link}")

# List of links to download HTML files from
names=[
"eth_getBlockByNumber",
"eth_getBlockTransactionCountByHash",
"eth_getBlockTransactionCountByNumber",
"eth_getCode",
"eth_getLogs",
"eth_getStorageAt",
"eth_getTransactionByBlockHashAndIndex",
"eth_getTransactionByBlockNumberAndIndex",
"eth_getTransactionByHash",
"eth_getTransactionCount",
"eth_getTransactionReceipt",
"eth_getUncleByBlockHashAndIndex",
"eth_getUncleByBlockNumberAndIndex",
"eth_getUncleCountByBlockHash",
"eth_getUncleCountByBlockNumber",
"eth_maxPriorityFeePerGas",
"eth_sendRawTransaction",
"eth_syncing",
"txpool_content",
"txpool_inspect",
"txpool_status",
"net_version",
"net_peerCount",
"web3_clientVersion",
"web3_sha3",
"debug_traceBlockByHash",
"debug_traceBlockByNumber",
"debug_traceCall",
"debug_traceTransaction",
"Solana RPC",
"getAccountInfo",
"getBalance",
"getBlock",
"getBlockCommitment",
"getBlockHeight",
"getBlockProduction",
"getBlocks",
"getBlocksWithLimit",
"getBlockTime",
"getClusterNodes",
"getEpochInfo",
"getEpochSchedule",
"getFeeForMessage",
"getFirstAvailableBlock",
"getGenesisHash",
"getHealth",
"getHighestSnapshotSlot",
"getIdentity",
"getInflationGovernor",
"getInflationRate",
"getInflationReward",
"getLatestBlockhash",
"getLeaderSchedule",
"getMaxRetransmitSlot",
"getMaxShredInsertSlot",
"getMinimumBalanceForRentExemption",
"getMultipleAccounts",
"getProgramAccounts",
"getRecentPerformanceSamples",
"getSignaturesForAddress",
"getSignatureStatuses",
"getSlot",
"getSlotLeader",
"getSlotLeaders",
"getStakeActivation",
"getStakeMinimumDelegation",
"getTokenAccountBalance",
"getTokenAccountsByOwner",
"getTokenSupply",
"getTransaction",
"getTransactionCount",
"getVersion",
"getVoteAccounts",
"isBlockhashValid",
"minimumLedgerSlot",
"requestAirdrop",
"sendTransaction",
"simulateTransaction",
"Arbitrum Nitro",
"eth_blockNumber",
"eth_call",
"eth_chainId",
"eth_estimateGas",
"eth_gasPrice",
"eth_getBalance",
"eth_getBlockByHash",
"eth_getBlockByNumber",
"eth_getBlockTransactionCountByHash",
"eth_getBlockTransactionCountByNumber",
"eth_getCode",
"eth_getFilterChanges",
"eth_getFilterLogs",
"eth_getLogs",
"eth_getStorageAt",
"eth_getTransactionByBlockHashAndIndex",
"eth_getTransactionByBlockNumberAndIndex",
"eth_getTransactionByHash",
"eth_getTransactionCount",
"eth_getTransactionReceipt",
"eth_getUncleCountByBlockHash",
"eth_getUncleCountByBlockNumber",
"eth_newBlockFilter",
"eth_newFilter",
"eth_newPendingTransactionFilter",
"eth_sendRawTransaction",
"eth_syncing",
"net_version",
"web3_clientVersion",
"debug_traceBlockByHash",
"debug_traceBlockByNumber",
"debug_traceCall",
"debug_traceTransaction",
"NEAR RPC",
"EXPERIMENTAL_changes-{account_changes}",
"EXPERIMENTAL_changes-{all_access_key_changes}",
"EXPERIMENTAL_changes-{contract_code_changes}",
"EXPERIMENTAL_changes-{data_changes}",
"EXPERIMENTAL_changes-{single_access_key_changes}",
"EXPERIMENTAL_changes_in_block",
"EXPERIMENTAL_receipt",
"EXPERIMENTAL_tx_status",
"block",
"broadcast_tx_async",
"broadcast_tx_commit",
"chunk",
"gas_price",
"network_info",
"query-{call_function}",
"query-{view_access_key_list}",
"query-{view_access_key}",
"query-{view_account}",
"query-{view_code}",
"query-{view_state}",
"status",
"tx",
"validators",
"Fantom RPC",
"dag_getEvent",
"dag_getEventPayload",
"dag_getHeads",
"eth_blockNumber",
"eth_call",
"eth_chainId",
"eth_estimateGas",
"eth_gasPrice",
"eth_getBalance",
"eth_getBlockByHash",
"eth_getBlockByNumber",
"eth_getBlockTransactionCountByHash",
"eth_getBlockTransactionCountByNumber",
"eth_getCode",
"eth_getFilterChanges",
"eth_getFilterLogs",
"eth_getLogs",
"eth_getStorageAt",
"eth_getTransactionByBlockHashAndIndex",
"eth_getTransactionByBlockNumberAndIndex",
"eth_getTransactionByHash",
"eth_getTransactionCount",
"eth_getTransactionReceipt",
"eth_getUncleCountByBlockHash",
"eth_getUncleCountByBlockNumber",
"eth_newBlockFilter",
"eth_newFilter",
"eth_newPendingTransactionFilter",
"eth_sendRawTransaction",
"eth_signTransaction",
"eth_syncing",
"ftm_currentEpoch",
"net_listening",
"net_peerCount",
"net_version",
"web3_clientVersion",
"Klaytn RPC",
"klay_accountCreated",
"klay_accounts",
"klay_encodeAccountKey",
"klay_decodeAccountKey",
"klay_getAccount",
"klay_getAccountKey",
"klay_getBalance",
"klay_getCode",
"klay_getTransactionCount",
"klay_isContractAccount",
"klay_sign",
"klay_blockNumber",
"klay_getHeaderByNumber",
"klay_getHeaderByHash",
"klay_getBlockByNumber",
"klay_getBlockByHash",
"klay_getBlockReceipts",
"klay_getBlockTransactionCountByNumber",
"klay_getBlockTransactionCountByHash",
"klay_getBlockWithConsensusInfoByNumber",
"klay_getBlockWithConsensusInfoByHash",
"klay_getCommittee",
"klay_getCommitteeSize",
"klay_getCouncil",
"klay_getCouncilSize",
"klay_getStorageAt",
"klay_syncing",
"klay_getRewards",
"klay_call",
"klay_estimateGas",
"klay_estimateComputationCost",
"klay_getTransactionByBlockHashAndIndex",
"klay_getTransactionByBlockNumberAndIndex",
"klay_getTransactionByHash",
"klay_getTransactionBySenderTxHash",
"klay_getTransactionReceipt",
"klay_getTransactionReceiptBySenderTxHash",
"klay_sendRawTransaction",
"klay_sendTransaction",
"klay_sendTransactionAsFeePayer",
"klay_signTransaction",
"klay_signTransactionAsFeePayer",
"klay_chainID",
"klay_clientVersion",
"klay_gasPrice",
"klay_gasPriceAt",
"klay_isParallelDBWrite",
"klay_isSenderTxHashIndexingEnabled",
"klay_protocolVersion",
"klay_rewardbase",
"klay_getFilterChanges",
"klay_getFilterLogs",
"klay_feeHistory",
"klay_maxPriorityFeePerGas",
"klay_sha3",
"net_networkID",
"net_listening",
"net_peerCount",
"net_peerCountByType",
"net_version",
"txError",
"Polygon zkEVM RPC",
"eth_blockNumber",
"eth_call",
"eth_chainId",
"eth_estimateGas",
"eth_gasPrice",
"eth_getBalance",
"eth_getBlockByHash",
"eth_getBlockByNumber",
"eth_getBlockTransactionCountByHash",
"eth_getBlockTransactionCountByNumber",
"eth_getCode",
"eth_getCompilers",
"eth_getFilterChanges",
"eth_getFilterLogs",
"eth_getLogs",
"eth_getStorageAt",
"eth_getTransactionByBlockHashAndIndex",
"eth_getTransactionByBlockNumberAndIndex",
"eth_getTransactionByHash",
"eth_getTransactionCount",
"eth_getTransactionReceipt",
"eth_getUncleByBlockHashAndIndex",
"eth_getUncleByBlockNumberAndIndex",
"eth_getUncleCountByBlockHash",
"eth_getUncleCountByBlockNumber",
"eth_newBlockFilter",
"eth_newFilter",
"eth_sendRawTransaction",
"eth_syncing",
"eth_uninstallFilter",
"net_version",
"txpool_content",
"web3_clientVersion",
"web3_sha3",
"debug_traceBlockByHash",
"debug_traceBlockByNumber",
"debug_traceCall",
"debug_traceTransaction",
"zkevm_batchNumber",
"zkevm_batchNumberByBlockNumber",
"zkevm_consolidatedBlockNumber",
"zkevm_getBatchByNumber",
"zkevm_isBlockConsolidated",
"zkevm_isBlockVirtualized",
"zkevm_verifiedBatchNumber",
"zkevm_virtualBatchNumber",
"SPACE ID universal name service API",
"Getting Started With Your API",
"Quick Start to build on SUI",
"Sui Mainnet JSON-RPC",
"Find API key & endpoint",
"NodeReal API Overview",
"Batch Requests",
"Account Information",
"eth_accountspost",
"eth_getCodepost",
"eth_getStorageAtpost",
"eth_getBalancepost",
"Chain Information",
"eth_chainIdpost",
"net_listeningpost",
"net_versionpost",
"web3_clientVersionpost",
"Gas",
"eth_gasPricepost",
"eth_estimateGaspost",
"Blocks",
"eth_getBlockByNumberpost",
"eth_getBlockTransactionCountByHashpost",
"eth_getBlockTransactionCountByNumberpost",
"eth_blockNumberpost",
"Event Logs",
"eth_getLogspost",
"eth_getFilterChangespost",
"eth_newFilterpost",
"eth_getFilterLogspost",
"eth_newBlockFilterpost",
"eth_newPendingTransactionFilterpost",
"EVM",
"eth_callpost",
"eth_sendRawTransactionpost",
"Transactions",
"eth_getTransactionByBlockHashAndIndexpost",
"eth_getTransactionByBlockNumberAndIndexpost",
"eth_getTransactionByHashpost",
"eth_getTransactionCountpost",
"eth_getTransactionReceiptpost",
"Uncle Blocks",
"eth_getUncleCountByBlockNumberpost",
"eth_getUncleCountByBlockHashpost",
"eth_getUncleByBlockHashAndIndexpost",
"eth_getUncleByBlockNumberAndIndexpost",
"Websockets",
"eth_unsubscribe",
"eth_subscribe",
"Account Information",
"eth_getBalancepost",
"eth_accountspost",
"eth_getStorageAtpost",
"eth_getCodepost",
"Event Logs",
"eth_getFilterLogspost",
"eth_getLogspost",
"eth_uninstallFilterpost",
"eth_newBlockFilterpost",
"eth_newPendingTransactionFilterpost",
"eth_getFilterChangespost",
"eth_newFilterpost",
"Chain Information",
"eth_chainIdpost",
"web3_clientVersionpost",
"net_listeningpost",
"net_versionpost",
"Uncle Blocks",
"eth_getUncleCountByBlockHashpost",
"eth_getUncleCountByBlockNumberpost",
"eth_getUncleByBlockNumberAndIndexpost",
"eth_getUncleByBlockHashAndIndexpost",
"Gas",
"eth_estimateGaspost",
"eth_gasPricepost",
"EVM",
"eth_sendRawTransactionpost",
"eth_callpost",
"Blocks",
"eth_blockNumberpost",
"eth_getBlockByNumberpost",
"eth_getBlockByNumberpost",
"eth_getBlockTransactionCountByHashpost",
"eth_getBlockTransactionCountByNumberpost",
"eth_getBlockByHashpost",
"Transaction",
"eth_getTransactionCountpost",
"eth_getTransactionByBlockHashAndIndexpost",
"eth_getTransactionByHashpost",
"eth_getTransactionByBlockNumberAndIndexpost",
"eth_getTransactionReceiptpost",
"WebSockets",
"eth_subscribe",
"eth_unsubscribe",
"Uniswap GraphQL API",
"PancakeSwap GraphQL API (v2)",
"PancakeSwap GraphQL API (v3)",
"Fungible Tokens API",
"nr_getTokenBalance20",
"nr_getTokenCount",
"nr_getTokenHolderCount",
"nr_getTokenHolders",
"nr_getTokenHoldingCount",
"nr_getTokenHoldings",
"nr_getTokenMeta",
"nr_getTotalSupply20",
"nr_historyTokenHolderSend",
"nr_getHistoryTokenHolder",
"NFT API",
"nr_getNFTCollectionHolderCount",
"nr_getNFTCollectionHolders",
"nr_getNFTHolderCount",
"nr_getNFTHolders",
"nr_getNFTHoldersWithBalance",
"nr_getNFTHoldingCount",
"nr_getNFTHoldings",
"nr_getNFTInventory",
"nr_getNFTMeta",
"nr_getNFTTokenCount",
"nr_getNFTTokens",
"nr_getNFTTokenOwners",
"nr_getSummedSupply1155",
"nr_getTokenBalance1155",
"nr_getTokenBalance721",
"nr_getTokenMeta",
"nr_getTotalSupply1155",
"nr_getTotalSupply721",
"Platform API",
"nr_health",
"Transaction Pool API",
"txpool_content",
"txpool_inspect",
"txpool_status",
"Transaction Receipts API",
"nr_getAssetTransfers",
"nr_getAssetTransfersCount",
"nr_getContractCreationTransaction",
"nr_getTransactionDetail",
"nr_getTransactionByAddress",
"nr_getTransactionByAddressCount",
"nr_getTransactionReceiptsByBlockHash",
"nr_getTransactionReceiptsByBlockNumber",
"nr_getTransferByTokenId",
"Debug API",
"debug_traceBlockByHashpost",
"debug_traceBlockByNumberpost",
"debug_traceTransactionpost",
"debug_traceCallpost",
"eth_getDiffAccountsWithScope",
"eth_getDiffAccounts",
"Debug Pro API",
"debug_jstraceBlockByHash",
"debug_jstraceBlockByNumber",
"debug_jstraceCall",
"debug_jstraceTransaction",
"trace_block",
"trace_call",
"trace_get",
"trace_filter",
"trace_transaction",
"trace_replayTransaction",
"trace_replayBlockTransactions",
"CU consumptionget",
"CU detailget",
"Account Information",
"eth_getStorageAtpost",
"eth_accountspost",
"eth_getBalancepost",
"eth_getCodepost",
"Blocks",
"eth_getBlockByHashpost",
"eth_getBlockTransactionCountByHashpost",
"eth_getBlockTransactionCountByNumberpost",
"eth_blockNumberpost",
"Chain Information",
"eth_chainIdpost",
"bor_getAuthorpost",
"net_versionpost",
"web3_clientVersionpost",
"net_listeningpost",
"bor_getCurrentProposerpost",
"bor_getCurrentValidatorspost",
"bor_getRootHashpost",
"EVM",
"eth_sendRawTransactionpost",
"eth_callpost",
"Gas",
"eth_estimateGaspost",
"eth_gasPricepost",
"Event Logs",
"eth_getFilterChangespost",
"eth_getFilterLogspost",
"eth_newPendingTransactionFilterpost",
"eth_newFilterpost",
"eth_uninstallFilterpost",
"eth_newBlockFilterpost",
"eth_getLogspost",
"Transactions",
"eth_getTransactionByBlockHashAndIndexpost",
"eth_getTransactionByHashpost",
"eth_getTransactionByBlockNumberAndIndexpost",
"eth_getTransactionCountpost",
"eth_getTransactionReceiptpost",
"eth_getTransactionReceiptsByBlockpost",
"Uncle Blocks",
"eth_getUncleByBlockHashAndIndexpost",
"eth_getUncleByBlockNumberAndIndexpost",
"eth_getUncleCountByBlockHashpost",
"eth_getUncleCountByBlockNumberpost",
"Websockets",
"eth_subscribe",
"eth_unsubscribe",
"Account Information",
"eth_getStorageAtpost",
"eth_accountspost",
"eth_getBalancepost",
"eth_getCodepost",
"Blocks",
"eth_getBlockByHashpost",
"eth_getBlockByNumberpost",
"eth_getBlockTransactionCountByHashpost",
"eth_blockNumberpost",
"eth_getBlockTransactionCountByNumberpost",
"Chain Information",
"eth_chainIdpost",
"net_listeningpost",
"web3_sha3post",
"web3_clientVersionpost",
"eth_syncingpost",
"net_versionpost",
"EVM",
"eth_sendRawTransactionpost",
"eth_callpost",
"Gas",
"eth_estimateGaspost",
"eth_gasPricepost",
"Event Logs",
"eth_getFilterChangespost",
"eth_getLogspost",
"eth_newPendingTransactionFilterpost",
"eth_uninstallFilterpost",
"eth_getFilterLogspost",
"eth_newBlockFilterpost",
"eth_newFilterpost",
"Transactions",
"eth_getTransactionByBlockHashAndIndexpost",
"eth_getTransactionByBlockNumberAndIndexpost",
"eth_getTransactionCountpost",
"eth_getTransactionByHashpost",
"eth_getTransactionReceiptpost",
"Uncle Blocks",
"eth_getUncleByBlockHashAndIndexpost",
"eth_getUncleByBlockNumberAndIndexpost",
"eth_getUncleCountByBlockHashpost",
"eth_getUncleCountByBlockNumberpost",
"Websockets",
"eth_subscribe",
"eth_unsubscribe",
"Beacon",
"Retrieve details of the chain's genesis.get",
"Get state SSZ HashTreeRootget",
"Get Fork object for requested stateget",
"Get state finality checkpointsget",
"Get validators from stateget",
"Get validator from state by idget",
"Get validator balances from stateget",
"Get all committees for a state.get",
"Get sync committees for a state.get",
"Get block headersget",
"Get block headerget",
"Publish a signed block.post",
"Publish a signed block.post",
"Get blockget",
"Get blockget",
"Get block rootget",
"Get block attestationsget",
"Get Attestations from operations poolget",
"Submit Attestation objects to nodepost",
"Get AttesterSlashings from operations poolget",
"Submit AttesterSlashing object to node's poolpost",
"Get ProposerSlashings from operations poolget",
"Submit ProposerSlashing object to node's poolpost",
"Submit sync committee signatures to nodepost",
"Get SignedVoluntaryExit from operations poolget",
"Submit SignedVoluntaryExit object to node's poolpost",
"ValidatorRequiredApi",
"Get attester dutiespost",
"Get block proposers dutiesget",
"Get sync committee dutiespost",
"Produce a new block, without signature.get",
"Produce a new block, without signature.get",
"Produce a new blinded block, without signature.get",
"Produce an attestation dataget",
"Get aggregated attestationget",
"Publish multiple aggregate and proofspost",
"Signal beacon node to prepare for a committee subnetpost",
"Subscribe to sync committee subnetspost",
"Produce a sync committee contributionget",
"Publish multiple contribution and proofspost",
"Provide beacon node with proposals for the given validators.post",
"Debug",
"Get full BeaconState objectget",
"Get full BeaconState objectget",
"Get fork choice leavesget",
"Get fork choice leavesget",
"Node",
"Get node network identityget",
"Get node network peersget",
"Get peerget",
"Get peer countget",
"Get version string of the running beacon node.get",
"Get node syncing statusget",
"Get health checkget",
"Config",
"Get scheduled upcoming forks.get",
"Get spec params.get",
"Get deposit contract address.get",
"Validator",
"Provide beacon node with registrations for the given validators to the external builder network.post",
"Events",
"Subscribe to beacon node eventsget",
"Get Started",
"Accounts",
"Get accountget",
"Get account resourcesget",
"Get account modulesget",
"Get account resourceget",
"Get account moduleget",
"General",
"Show OpenAPI explorerget",
"Check basic node healthget",
"Get ledger infoget",
"Blocks",
"Get blocks by heightget",
"Get blocks by versionget",
"Events",
"Get events by event keyget",
"Get events by creation numberget",
"Get events by event handleget",
"Tables",
"Get table itempost",
"Transactions",
"Get transactionsget",
"Submit transactionpost",
"Get transaction by hashget",
"Get transaction by versionget",
"Get account transactionsget",
"Submit batch transactionspost",
"Simulate transactionpost",
"Encode submissionpost",
"Estimate gas priceget",
"NFTScan API",
"Get NFTs by account",
"Get all NFTs by account",
"Get minted NFTs by account",
"Get NFTs by contract",
"Get single NFT",
"Get multiple NFTs",
"Search NFTs",
"Get NFTs by attributes",
"Get all multi-chain NFTs by account",
"Get transactions by account",
"Get transactions by contract",
"Get transactions by NFT",
"Search transactions",
"Get transactions by to address",
"Get transactions by hash",
"Get an NFT collection",
"Search NFT collections",
"Get NFT collections by account",
"Get NFT collections by ranking",
"Trade Ranking",
"Mint Ranking",
"Mint Amount",
"Traders Ranking",
"Gas Ranking",
"Collection Ranking",
"Marketplace Ranking",
"Market Cap Ranking",
"Collection Statistics",
"Collection Trade Distribution",
"Collection Trending Statistics",
"Blue Chip",
"Account Overview",
"Account Holding Distribution",
"Collection Overview",
"Refresh NFT metadata",
"Refresh NFT metadata by contract",
"Get latest block number",
"Get NFT amount by account",
"Get NFT owners by contract",
"Get owners by an NFT",
"Covalent API",
"Balances",
"Transactions",
"Arbitrum Nova",
"eth_blockNumber",
"eth_call",
"eth_chainId",
"eth_estimateGas",
"eth_gasPrice",
"eth_getBalance",
"eth_getBlockByHash",
"eth_getBlockByNumber",
"eth_getBlockTransactionCountByHash",
"eth_getBlockTransactionCountByNumber",
"eth_getCode",
"eth_getFilterChanges",
"eth_getFilterLogs",
"eth_getLogs",
"eth_getStorageAt",
"eth_getTransactionByBlockHashAndIndex",
"eth_getTransactionByBlockNumberAndIndex",
"eth_getTransactionByHash",
"eth_getTransactionCount",
"eth_getTransactionReceipt",
"eth_getUncleCountByBlockHash",
"eth_getUncleCountByBlockNumber",
"eth_newBlockFilter",
"eth_newFilter",
"eth_newPendingTransactionFilter",
"eth_sendRawTransaction",
"eth_syncing",
"net_version",
"web3_clientVersion",
"Avalanche Contract Chain (C-Chain)",
"avax.getAtomicTx",
"avax.getUTXOs",
"avax.issueTx",
"avax.getAtomicTxStatus",
"eth_baseFee",
"eth_blockNumber",
"eth_call",
"eth_chainId",
"eth_estimateGas",
"eth_gasPrice",
"eth_getAssetBalance",
"eth_getBalance",
"eth_getBlockByHash",
"eth_getBlockByNumber",
"eth_getBlockTransactionCountByHash",
"eth_getBlockTransactionCountByNumber",
"eth_getCode",
"eth_getLogs",
"eth_getStorageAt",
"eth_getTransactionByBlockHashAndIndex",
"eth_getTransactionByBlockNumberAndIndex",
"eth_getTransactionByHash",
"eth_getTransactionCount",
"eth_getTransactionReceipt",
"eth_getUncleByBlockHashAndIndex",
"eth_getUncleByBlockNumberAndIndex",
"eth_getUncleCountByBlockHash",
"eth_getUncleCountByBlockNumber",
"eth_maxPriorityFeePerGas",
"eth_sendRawTransaction",
"eth_syncing",
"txpool_content",
"txpool_inspect",
"txpool_status",
"net_version",
"net_peerCount",
"web3_clientVersion",
"web3_sha3",
"debug_traceBlockByHash",
"debug_traceBlockByNumber",
"debug_traceCall",
"debug_traceTransaction",
"Solana RPC",
"getAccountInfo",
"getBalance",
"getBlock",
"getBlockCommitment",
"getBlockHeight",
"getBlockProduction",
"getBlocks",
"getBlocksWithLimit",
"getBlockTime",
"getClusterNodes",
"getEpochInfo",
"getEpochSchedule",
"getFeeForMessage",
"getFirstAvailableBlock",
"getGenesisHash",
"getHealth",
"getHighestSnapshotSlot",
"getIdentity",
"getInflationGovernor",
"getInflationRate",
"getInflationReward",
"getLatestBlockhash",
"getLeaderSchedule",
"getMaxRetransmitSlot",
"getMaxShredInsertSlot",
"getMinimumBalanceForRentExemption",
"getMultipleAccounts",
"getProgramAccounts",
"getRecentPerformanceSamples",
"getSignaturesForAddress",
"getSignatureStatuses",
"getSlot",
"getSlotLeader",
"getSlotLeaders",
"getStakeActivation",
"getStakeMinimumDelegation",
"getTokenAccountBalance",
"getTokenAccountsByOwner",
"getTokenSupply",
"getTransaction",
"getTransactionCount",
"getVersion",
"getVoteAccounts",
"isBlockhashValid",
"minimumLedgerSlot",
"requestAirdrop",
"sendTransaction",
"simulateTransaction",
"Arbitrum Nitro",
"eth_blockNumber",
"eth_call",
"eth_chainId",
"eth_estimateGas",
"eth_gasPrice",
"eth_getBalance",
"eth_getBlockByHash",
"eth_getBlockByNumber",
"eth_getBlockTransactionCountByHash",
"eth_getBlockTransactionCountByNumber",
"eth_getCode",
"eth_getFilterChanges",
"eth_getFilterLogs",
"eth_getLogs",
"eth_getStorageAt",
"eth_getTransactionByBlockHashAndIndex",
"eth_getTransactionByBlockNumberAndIndex",
"eth_getTransactionByHash",
"eth_getTransactionCount",
"eth_getTransactionReceipt",
"eth_getUncleCountByBlockHash",
"eth_getUncleCountByBlockNumber",
"eth_newBlockFilter",
"eth_newFilter",
"eth_newPendingTransactionFilter",
"eth_sendRawTransaction",
"eth_syncing",
"net_version",
"web3_clientVersion",
"debug_traceBlockByHash",
"debug_traceBlockByNumber",
"debug_traceCall",
"debug_traceTransaction",
"NEAR RPC",
"EXPERIMENTAL_changes-{account_changes}",
"EXPERIMENTAL_changes-{all_access_key_changes}",
"EXPERIMENTAL_changes-{contract_code_changes}",
"EXPERIMENTAL_changes-{data_changes}",
"EXPERIMENTAL_changes-{single_access_key_changes}",
"EXPERIMENTAL_changes_in_block",
"EXPERIMENTAL_receipt",
"EXPERIMENTAL_tx_status",
"block",
"broadcast_tx_async",
"broadcast_tx_commit",
"chunk",
"gas_price",
"network_info",
"query-{call_function}",
"query-{view_access_key_list}",
"query-{view_access_key}",
"query-{view_account}",
"query-{view_code}",
"query-{view_state}",
"status",
"tx",
"validators",
"Fantom RPC",
"dag_getEvent",
"dag_getEventPayload",
"dag_getHeads",
"eth_blockNumber",
"eth_call",
"eth_chainId",
"eth_estimateGas",
"eth_gasPrice",
"eth_getBalance",
"eth_getBlockByHash",
"eth_getBlockByNumber",
"eth_getBlockTransactionCountByHash",
"eth_getBlockTransactionCountByNumber",
"eth_getCode",
"eth_getFilterChanges",
"eth_getFilterLogs",
"eth_getLogs",
"eth_getStorageAt",
"eth_getTransactionByBlockHashAndIndex",
"eth_getTransactionByBlockNumberAndIndex",
"eth_getTransactionByHash",
"eth_getTransactionCount",
"eth_getTransactionReceipt",
"eth_getUncleCountByBlockHash",
"eth_getUncleCountByBlockNumber",
"eth_newBlockFilter",
"eth_newFilter",
"eth_newPendingTransactionFilter",
"eth_sendRawTransaction",
"eth_signTransaction",
"eth_syncing",
"ftm_currentEpoch",
"net_listening",
"net_peerCount",
"net_version",
"web3_clientVersion",
"Klaytn RPC",
"klay_accountCreated",
"klay_accounts",
"klay_encodeAccountKey",
"klay_decodeAccountKey",
"klay_getAccount",
"klay_getAccountKey",
"klay_getBalance",
"klay_getCode",
"klay_getTransactionCount",
"klay_isContractAccount",
"klay_sign",
"klay_blockNumber",
"klay_getHeaderByNumber",
"klay_getHeaderByHash",
"klay_getBlockByNumber",
"klay_getBlockByHash",
"klay_getBlockReceipts",
"klay_getBlockTransactionCountByNumber",
"klay_getBlockTransactionCountByHash",
"klay_getBlockWithConsensusInfoByNumber",
"klay_getBlockWithConsensusInfoByHash",
"klay_getCommittee",
"klay_getCommitteeSize",
"klay_getCouncil",
"klay_getCouncilSize",
"klay_getStorageAt",
"klay_syncing",
"klay_getRewards",
"klay_call",
"klay_estimateGas",
"klay_estimateComputationCost",
"klay_getTransactionByBlockHashAndIndex",
"klay_getTransactionByBlockNumberAndIndex",
"klay_getTransactionByHash",
"klay_getTransactionBySenderTxHash",
"klay_getTransactionReceipt",
"klay_getTransactionReceiptBySenderTxHash",
"klay_sendRawTransaction",
"klay_sendTransaction",
"klay_sendTransactionAsFeePayer",
"klay_signTransaction",
"klay_signTransactionAsFeePayer",
"klay_chainID",
"klay_clientVersion",
"klay_gasPrice",
"klay_gasPriceAt",
"klay_isParallelDBWrite",
"klay_isSenderTxHashIndexingEnabled",
"klay_protocolVersion",
"klay_rewardbase",
"klay_getFilterChanges",
"klay_getFilterLogs",
"klay_feeHistory",
"klay_maxPriorityFeePerGas",
"klay_sha3",
"net_networkID",
"net_listening",
"net_peerCount",
"net_peerCountByType",
"net_version",
"txError",
"Polygon zkEVM RPC",
"eth_blockNumber",
"eth_call",
"eth_chainId",
"eth_estimateGas",
"eth_gasPrice",
"eth_getBalance",
"eth_getBlockByHash",
"eth_getBlockByNumber",
"eth_getBlockTransactionCountByHash",
"eth_getBlockTransactionCountByNumber",
"eth_getCode",
"eth_getCompilers",
"eth_getFilterChanges",
"eth_getFilterLogs",
"eth_getLogs",
"eth_getStorageAt",
"eth_getTransactionByBlockHashAndIndex",
"eth_getTransactionByBlockNumberAndIndex",
"eth_getTransactionByHash",
"eth_getTransactionCount",
"eth_getTransactionReceipt",
"eth_getUncleByBlockHashAndIndex",
"eth_getUncleByBlockNumberAndIndex",
"eth_getUncleCountByBlockHash",
"eth_getUncleCountByBlockNumber",
"eth_newBlockFilter",
"eth_newFilter",
"eth_sendRawTransaction",
"eth_syncing",
"eth_uninstallFilter",
"net_version",
"txpool_content",
"web3_clientVersion",
"web3_sha3",
"debug_traceBlockByHash",
"debug_traceBlockByNumber",
"debug_traceCall",
"debug_traceTransaction",
"zkevm_batchNumber",
"zkevm_batchNumberByBlockNumber",
"zkevm_consolidatedBlockNumber",
"zkevm_getBatchByNumber",
"zkevm_isBlockConsolidated",
"zkevm_isBlockVirtualized",
"zkevm_verifiedBatchNumber",
"zkevm_virtualBatchNumber",
"SPACE ID universal name service API",
"Getting Started With Your API",
"Quick Start to build on SUI",
"Sui Mainnet JSON-RPC"]

link_list = ["https://docs.nodereal.io/reference/eth_getbalance","https://docs.nodereal.io/reference/eth_getblockbyhash","https://docs.nodereal.io/reference/eth_getblockbynumber","https://docs.nodereal.io/reference/eth_getblocktransactioncountbyhash","https://docs.nodereal.io/reference/eth_getblocktransactioncountbynumber","https://docs.nodereal.io/reference/eth_getcode","https://docs.nodereal.io/reference/eth_getfilterchanges","https://docs.nodereal.io/reference/eth_getfilterlogs","https://docs.nodereal.io/reference/eth_getlogs","https://docs.nodereal.io/reference/eth_getstorageat","https://docs.nodereal.io/reference/eth_gettransactionbyblockhashandindex","https://docs.nodereal.io/reference/eth_gettransactionbyblocknumberandindex","https://docs.nodereal.io/reference/eth_gettransactionbyhash","https://docs.nodereal.io/reference/eth_gettransactioncount-1","https://docs.nodereal.io/reference/eth_gettransactionreceipt","https://docs.nodereal.io/reference/eth_getunclecountbyblockhash","https://docs.nodereal.io/reference/eth_getunclecountbyblocknumber","https://docs.nodereal.io/reference/eth_newblockfilter","https://docs.nodereal.io/reference/eth_newfilter","https://docs.nodereal.io/reference/eth_newpendingtransactionfilter","https://docs.nodereal.io/reference/eth_sendrawtransaction","https://docs.nodereal.io/reference/eth_syncing","https://docs.nodereal.io/reference/net_version","https://docs.nodereal.io/reference/web3_clientversion","https://docs.nodereal.io/reference/avalanche-c-chain-avax","https://docs.nodereal.io/reference/avaxgetatomictx","https://docs.nodereal.io/reference/avaxgetutxos","https://docs.nodereal.io/reference/avaxissuetx","https://docs.nodereal.io/reference/avaxgetatomictxstatus","https://docs.nodereal.io/reference/eth_basefee","https://docs.nodereal.io/reference/eth_blocknumber-1","https://docs.nodereal.io/reference/eth_call-1","https://docs.nodereal.io/reference/eth_chainid-1","https://docs.nodereal.io/reference/eth_estimategas-1","https://docs.nodereal.io/reference/eth_gasprice-1","https://docs.nodereal.io/reference/eth_getassetbalance","https://docs.nodereal.io/reference/eth_getbalance-1","https://docs.nodereal.io/reference/eth_getblockbyhash-1","https://docs.nodereal.io/reference/eth_getblockbynumber-1","https://docs.nodereal.io/reference/eth_getblocktransactioncountbyhash-1","https://docs.nodereal.io/reference/eth_getblocktransactioncountbynumber-1","https://docs.nodereal.io/reference/eth_getcode-1","https://docs.nodereal.io/reference/eth_getlogs-1","https://docs.nodereal.io/reference/eth_getstorageat-1","https://docs.nodereal.io/reference/eth_gettransactionbyblockhashandindex-1","https://docs.nodereal.io/reference/eth_gettransactionbyblocknumberandindex-1","https://docs.nodereal.io/reference/eth_gettransactionbyhash-1","https://docs.nodereal.io/reference/eth_gettransactioncount-2","https://docs.nodereal.io/reference/eth_gettransactionreceipt-1","https://docs.nodereal.io/reference/eth_getunclebyblockhashandindex","https://docs.nodereal.io/reference/eth_getunclebyblocknumberandindex","https://docs.nodereal.io/reference/eth_getunclecountbyblockhash-1","https://docs.nodereal.io/reference/eth_getunclecountbyblocknumber-1","https://docs.nodereal.io/reference/eth_maxpriorityfeepergas","https://docs.nodereal.io/reference/eth_sendrawtransaction-1","https://docs.nodereal.io/reference/eth_syncing-1","https://docs.nodereal.io/reference/txpool_content-1","https://docs.nodereal.io/reference/txpool_inspect-1","https://docs.nodereal.io/reference/txpool_status-1","https://docs.nodereal.io/reference/net_version-1","https://docs.nodereal.io/reference/net_peercount","https://docs.nodereal.io/reference/web3_clientversion-1","https://docs.nodereal.io/reference/web3_sha3","https://docs.nodereal.io/reference/debug_traceblockbyhash-1","https://docs.nodereal.io/reference/debug_traceblockbynumber-1","https://docs.nodereal.io/reference/debug_tracecall-1","https://docs.nodereal.io/reference/debug_tracetransaction-1","https://docs.nodereal.io/reference/solana-rpc","https://docs.nodereal.io/reference/getaccountinfo","https://docs.nodereal.io/reference/getbalance","https://docs.nodereal.io/reference/getblock","https://docs.nodereal.io/reference/getblockcommitment","https://docs.nodereal.io/reference/getblockheight","https://docs.nodereal.io/reference/getblockproduction","https://docs.nodereal.io/reference/getblocks","https://docs.nodereal.io/reference/getblockswithlimit","https://docs.nodereal.io/reference/getblocktime","https://docs.nodereal.io/reference/getclusternodes","https://docs.nodereal.io/reference/getepochinfo","https://docs.nodereal.io/reference/getepochschedule","https://docs.nodereal.io/reference/getfeeformessage","https://docs.nodereal.io/reference/getfirstavailableblock","https://docs.nodereal.io/reference/getgenesishash","https://docs.nodereal.io/reference/gethealth-1","https://docs.nodereal.io/reference/gethighestsnapshotslot","https://docs.nodereal.io/reference/getidentity","https://docs.nodereal.io/reference/getinflationgovernor","https://docs.nodereal.io/reference/getinflationrate","https://docs.nodereal.io/reference/getinflationreward","https://docs.nodereal.io/reference/getlatestblockhash","https://docs.nodereal.io/reference/getleaderschedule","https://docs.nodereal.io/reference/getmaxretransmitslot","https://docs.nodereal.io/reference/getmaxshredinsertslot","https://docs.nodereal.io/reference/getminimumbalanceforrentexemption","https://docs.nodereal.io/reference/getmultipleaccounts","https://docs.nodereal.io/reference/getprogramaccounts","https://docs.nodereal.io/reference/getrecentperformancesamples","https://docs.nodereal.io/reference/getsignaturesforaddress","https://docs.nodereal.io/reference/getsignaturestatuses","https://docs.nodereal.io/reference/getslot","https://docs.nodereal.io/reference/getslotleader","https://docs.nodereal.io/reference/getslotleaders","https://docs.nodereal.io/reference/getstakeactivation","https://docs.nodereal.io/reference/getstakeminimumdelegation","https://docs.nodereal.io/reference/gettokenaccountbalance","https://docs.nodereal.io/reference/gettokenaccountsbyowner","https://docs.nodereal.io/reference/gettokensupply","https://docs.nodereal.io/reference/gettransaction","https://docs.nodereal.io/reference/gettransactioncount","https://docs.nodereal.io/reference/getversion","https://docs.nodereal.io/reference/getvoteaccounts","https://docs.nodereal.io/reference/isblockhashvalid","https://docs.nodereal.io/reference/minimumledgerslot","https://docs.nodereal.io/reference/requestairdrop","https://docs.nodereal.io/reference/sendtransaction","https://docs.nodereal.io/reference/simulatetransaction","https://docs.nodereal.io/reference/arbitrum-nitro","https://docs.nodereal.io/reference/eth_blocknumber-2","https://docs.nodereal.io/reference/eth_call-2","https://docs.nodereal.io/reference/eth_chainid-2","https://docs.nodereal.io/reference/eth_estimategas-2","https://docs.nodereal.io/reference/eth_gasprice-2","https://docs.nodereal.io/reference/eth_getbalance-2","https://docs.nodereal.io/reference/eth_getblockbyhash-2","https://docs.nodereal.io/reference/eth_getblockbynumber-2","https://docs.nodereal.io/reference/eth_getblocktransactioncountbyhash-2","https://docs.nodereal.io/reference/eth_getblocktransactioncountbynumber-2","https://docs.nodereal.io/reference/eth_getcode-2","https://docs.nodereal.io/reference/eth_getfilterchanges-1","https://docs.nodereal.io/reference/eth_getfilterlogs-1","https://docs.nodereal.io/reference/eth_getlogs-2","https://docs.nodereal.io/reference/eth_getstorageat-2","https://docs.nodereal.io/reference/eth_gettransactionbyblockhashandindex-2","https://docs.nodereal.io/reference/eth_gettransactionbyblocknumberandindex-2","https://docs.nodereal.io/reference/eth_gettransactionbyhash-2","https://docs.nodereal.io/reference/eth_gettransactioncount","https://docs.nodereal.io/reference/eth_gettransactionreceipt-2","https://docs.nodereal.io/reference/eth_getunclecountbyblockhash-2","https://docs.nodereal.io/reference/eth_getunclecountbyblocknumber-2","https://docs.nodereal.io/reference/eth_newblockfilter-1","https://docs.nodereal.io/reference/eth_newfilter-1","https://docs.nodereal.io/reference/eth_newpendingtransactionfilter-1","https://docs.nodereal.io/reference/eth_sendrawtransaction-2","https://docs.nodereal.io/reference/eth_syncing-2","https://docs.nodereal.io/reference/net_version-2","https://docs.nodereal.io/reference/web3_clientversion-2","https://docs.nodereal.io/reference/debug_traceblockbyhash-2","https://docs.nodereal.io/reference/debug_traceblockbynumber-2","https://docs.nodereal.io/reference/debug_tracecall-2","https://docs.nodereal.io/reference/debug_tracetransaction-2","https://docs.nodereal.io/reference/near-rpc","https://docs.nodereal.io/reference/experimental_changes-account_changes","https://docs.nodereal.io/reference/experimental_changes-all_access_key_changes","https://docs.nodereal.io/reference/experimental_changes-contract_code_changes","https://docs.nodereal.io/reference/experimental_changes-data_changes","https://docs.nodereal.io/reference/experimental_changes-single_access_key_changes","https://docs.nodereal.io/reference/experimental_changes_in_block","https://docs.nodereal.io/reference/experimental_receipt","https://docs.nodereal.io/reference/experimental_tx_status","https://docs.nodereal.io/reference/block","https://docs.nodereal.io/reference/broadcast_tx_async","https://docs.nodereal.io/reference/broadcast_tx_commit","https://docs.nodereal.io/reference/chunk","https://docs.nodereal.io/reference/gas_price","https://docs.nodereal.io/reference/network_info","https://docs.nodereal.io/reference/query-call_function","https://docs.nodereal.io/reference/query-view_access_key_list","https://docs.nodereal.io/reference/query-view_access_key","https://docs.nodereal.io/reference/query-view_account","https://docs.nodereal.io/reference/query-view_code","https://docs.nodereal.io/reference/query-view_state","https://docs.nodereal.io/reference/status","https://docs.nodereal.io/reference/tx","https://docs.nodereal.io/reference/validators","https://docs.nodereal.io/reference/fantom","https://docs.nodereal.io/reference/dag_getevent","https://docs.nodereal.io/reference/dag_geteventpayload","https://docs.nodereal.io/reference/dag_getheads","https://docs.nodereal.io/reference/eth_blocknumber-3","https://docs.nodereal.io/reference/eth_call-3","https://docs.nodereal.io/reference/eth_chainid-3","https://docs.nodereal.io/reference/eth_estimategas-3","https://docs.nodereal.io/reference/eth_gasprice-3","https://docs.nodereal.io/reference/eth_getbalance-3","https://docs.nodereal.io/reference/eth_getblockbyhash-3","https://docs.nodereal.io/reference/eth_getblockbynumber-3","https://docs.nodereal.io/reference/eth_getblocktransactioncountbyhash-3","https://docs.nodereal.io/reference/eth_getblocktransactioncountbynumber-3","https://docs.nodereal.io/reference/eth_getcode-3","https://docs.nodereal.io/reference/eth_getfilterchanges-2","https://docs.nodereal.io/reference/eth_getfilterlogs-2","https://docs.nodereal.io/reference/eth_getlogs-3","https://docs.nodereal.io/reference/eth_getstorageat-3","https://docs.nodereal.io/reference/eth_gettransactionbyblockhashandindex-3","https://docs.nodereal.io/reference/eth_gettransactionbyblocknumberandindex-3","https://docs.nodereal.io/reference/eth_gettransactionbyhash-3","https://docs.nodereal.io/reference/eth_gettransactioncount-3","https://docs.nodereal.io/reference/eth_gettransactionreceipt-3","https://docs.nodereal.io/reference/eth_getunclecountbyblockhash-3","https://docs.nodereal.io/reference/eth_getunclecountbyblocknumber-3","https://docs.nodereal.io/reference/eth_newblockfilter-2","https://docs.nodereal.io/reference/eth_newfilter-2","https://docs.nodereal.io/reference/eth_newpendingtransactionfilter-2","https://docs.nodereal.io/reference/eth_sendrawtransaction-3","https://docs.nodereal.io/reference/eth_signtransaction","https://docs.nodereal.io/reference/eth_syncing-3","https://docs.nodereal.io/reference/ftm_currentepoch","https://docs.nodereal.io/reference/net_listening","https://docs.nodereal.io/reference/net_peercount-1","https://docs.nodereal.io/reference/net_version-3","https://docs.nodereal.io/reference/web3_clientversion-3","https://docs.nodereal.io/reference/klaytn-rpc","https://docs.nodereal.io/reference/klay_accountcreated","https://docs.nodereal.io/reference/klay_accounts","https://docs.nodereal.io/reference/klay_encodeaccountkey","https://docs.nodereal.io/reference/klay_decodeaccountkey","https://docs.nodereal.io/reference/klay_getaccount","https://docs.nodereal.io/reference/klay_getaccountkey","https://docs.nodereal.io/reference/klay_getbalance","https://docs.nodereal.io/reference/klay_getcode","https://docs.nodereal.io/reference/klay_gettransactioncount","https://docs.nodereal.io/reference/klay_iscontractaccount","https://docs.nodereal.io/reference/klay_sign","https://docs.nodereal.io/reference/klay_blocknumber","https://docs.nodereal.io/reference/klay_getheaderbynumber","https://docs.nodereal.io/reference/klay_getheaderbyhash","https://docs.nodereal.io/reference/klay_getblockbynumber","https://docs.nodereal.io/reference/klay_getblockbyhash","https://docs.nodereal.io/reference/klay_getblockreceipts","https://docs.nodereal.io/reference/klay_getblocktransactioncountbynumber","https://docs.nodereal.io/reference/klay_getblocktransactioncountbyhash","https://docs.nodereal.io/reference/klay_getblockwithconsensusinfobynumber","https://docs.nodereal.io/reference/klay_getblockwithconsensusinfobyhash","https://docs.nodereal.io/reference/klay_getcommittee","https://docs.nodereal.io/reference/klay_getcommitteesize","https://docs.nodereal.io/reference/klay_getcouncil","https://docs.nodereal.io/reference/klay_getcouncilsize","https://docs.nodereal.io/reference/klay_getstorageat","https://docs.nodereal.io/reference/klay_syncing","https://docs.nodereal.io/reference/klay_getrewards","https://docs.nodereal.io/reference/klay_call","https://docs.nodereal.io/reference/klay_estimategas","https://docs.nodereal.io/reference/klay_estimatecomputationcost","https://docs.nodereal.io/reference/klay_gettransactionbyblockhashandindex","https://docs.nodereal.io/reference/klay_gettransactionbyblocknumberandindex","https://docs.nodereal.io/reference/klay_gettransactionbyhash","https://docs.nodereal.io/reference/klay_gettransactionbysendertxhash","https://docs.nodereal.io/reference/klay_gettransactionreceipt","https://docs.nodereal.io/reference/klay_gettransactionreceiptbysendertxhash","https://docs.nodereal.io/reference/klay_sendrawtransaction","https://docs.nodereal.io/reference/klay_sendtransaction","https://docs.nodereal.io/reference/klay_sendtransactionasfeepayer","https://docs.nodereal.io/reference/klay_signtransaction","https://docs.nodereal.io/reference/klay_signtransactionasfeepayer","https://docs.nodereal.io/reference/klay_chainid","https://docs.nodereal.io/reference/klay_clientversion","https://docs.nodereal.io/reference/klay_gasprice","https://docs.nodereal.io/reference/klay_gaspriceat","https://docs.nodereal.io/reference/klay_isparalleldbwrite","https://docs.nodereal.io/reference/klay_issendertxhashindexingenabled","https://docs.nodereal.io/reference/klay_protocolversion","https://docs.nodereal.io/reference/klay_rewardbase","https://docs.nodereal.io/reference/klay_getfilterchanges","https://docs.nodereal.io/reference/klay_getfilterlogs","https://docs.nodereal.io/reference/klay_feehistory","https://docs.nodereal.io/reference/klay_maxpriorityfeepergas","https://docs.nodereal.io/reference/klay_sha3","https://docs.nodereal.io/reference/net_networkid","https://docs.nodereal.io/reference/net_listening-1","https://docs.nodereal.io/reference/net_peercount-2","https://docs.nodereal.io/reference/net_peercountbytype","https://docs.nodereal.io/reference/net_version-4","https://docs.nodereal.io/reference/txerror","https://docs.nodereal.io/reference/polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_blocknumber-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_call-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_chainid-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_estimategas-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_gasprice-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getbalance-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getblockbyhash-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getblockbynumber-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getblocktransactioncountbyhash-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getblocktransactioncountbynumber-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getcode-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getcompilers-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getfilterchanges-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getfilterlogs-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getlogs-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getstorageat-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_gettransactionbyblockhashandindex-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_gettransactionbyblocknumberandindex-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_gettransactionbyhash-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_gettransactioncount-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_gettransactionreceipt-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getunclebyblockhashandindex-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getunclebyblocknumberandindex-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getunclecountbyblockhash-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_getunclecountbyblocknumber-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_newblockfilter-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_newfilter-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_sendrawtransaction-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_syncing-polygon-zkevm-rpc","https://docs.nodereal.io/reference/eth_uninstallfilter-polygon-zkevm-rpc","https://docs.nodereal.io/reference/net_version-polygon-zkevm-rpc","https://docs.nodereal.io/reference/txpool_content-polygon-zkevm-rpc","https://docs.nodereal.io/reference/web3_clientversion-polygon-zkevm-rpc","https://docs.nodereal.io/reference/web3_sha3-polygon-zkevm-rpc","https://docs.nodereal.io/reference/debug_traceblockbyhash-polygon-zkevm-rpc","https://docs.nodereal.io/reference/debug_traceblockbynumber-polygon-zkevm-rpc","https://docs.nodereal.io/reference/debug_tracecall-polygon-zkevm-rpc","https://docs.nodereal.io/reference/debug_tracetransaction-polygon-zkevm-rpc","https://docs.nodereal.io/reference/zkevm_batchnumber","https://docs.nodereal.io/reference/zkevm_batchnumberbyblocknumber","https://docs.nodereal.io/reference/zkevm_consolidatedblocknumber","https://docs.nodereal.io/reference/zkevm_getbatchbynumber","https://docs.nodereal.io/reference/zkevm_isblockconsolidated","https://docs.nodereal.io/reference/zkevm_isblockvirtualized","https://docs.nodereal.io/reference/zkevm_verifiedbatchnumber","https://docs.nodereal.io/reference/zkevm_virtualbatchnumber","https://docs.nodereal.io/reference/space-id-universal-name-service-api","https://docs.nodereal.io/reference/getting-started-with-your-api-1","https://docs.nodereal.io/reference/quick-start-to-build-on-sui","https://docs.nodereal.io/reference/sui-mainnet-json-rpc","https://docs.nodereal.io/reference/find-api-key-endpoint","https://docs.nodereal.io/reference/getting-started-with-your-api","https://docs.nodereal.io/reference/batch-requests","https://docs.nodereal.io/reference/account-information-4","https://docs.nodereal.io/reference/eth-accounts-bsc","https://docs.nodereal.io/reference/eth-getcode-bsc","https://docs.nodereal.io/reference/eth-getstorageat-bsc","https://docs.nodereal.io/reference/eth-getbalance-bsc","https://docs.nodereal.io/reference/chain-information-4","https://docs.nodereal.io/reference/eth-chainid-bsc","https://docs.nodereal.io/reference/net-listening-bsc","https://docs.nodereal.io/reference/net-version-bsc","https://docs.nodereal.io/reference/web3-clientversion-bsc","https://docs.nodereal.io/reference/gas-4","https://docs.nodereal.io/reference/eth-gasprice-bsc","https://docs.nodereal.io/reference/eth-estimategas-bsc","https://docs.nodereal.io/reference/blocks-5","https://docs.nodereal.io/reference/eth-getblockbynumber-bsc","https://docs.nodereal.io/reference/eth-getblocktransactioncountbyhash-bsc","https://docs.nodereal.io/reference/eth-getblocktransactioncountbynumber-bsc","https://docs.nodereal.io/reference/eth-blocknumber-bsc","https://docs.nodereal.io/reference/event-logs-4","https://docs.nodereal.io/reference/eth-getlogs-bsc","https://docs.nodereal.io/reference/eth-getfilterchanges-bsc","https://docs.nodereal.io/reference/eth-newfilter-bsc","https://docs.nodereal.io/reference/eth-getfilterlogs-bsc","https://docs.nodereal.io/reference/eth-newblockfilter-bsc","https://docs.nodereal.io/reference/eth-newpendingtransactionfilter-bsc","https://docs.nodereal.io/reference/evm-4","https://docs.nodereal.io/reference/eth-call-bsc","https://docs.nodereal.io/reference/eth-sendrawtransaction-bsc","https://docs.nodereal.io/reference/transactions-3","https://docs.nodereal.io/reference/eth-gettransactionbyblockhashandindex-bsc","https://docs.nodereal.io/reference/eth-gettransactionbyblocknumberandindex-bsc","https://docs.nodereal.io/reference/eth-gettransactionbyhash-bsc","https://docs.nodereal.io/reference/eth_gettransactioncount-bsc","https://docs.nodereal.io/reference/eth-gettransactionreceipt-bsc","https://docs.nodereal.io/reference/uncle-blocks-4","https://docs.nodereal.io/reference/eth-getunclecountbyblocknumber-bsc","https://docs.nodereal.io/reference/eth-getunclecountbyblockhash-bsc","https://docs.nodereal.io/reference/eth-getunclebyblockhashandindex-bsc","https://docs.nodereal.io/reference/eth-getunclebyblocknumberandindex-bsc","https://docs.nodereal.io/reference/websockets-4","https://docs.nodereal.io/reference/eth-unsubscribe-bsc","https://docs.nodereal.io/reference/eth-subscribe-bsc","https://docs.nodereal.io/reference/account-information-ethereum","https://docs.nodereal.io/reference/eth-getbalance-eth","https://docs.nodereal.io/reference/eth-accounts-eth","https://docs.nodereal.io/reference/eth-getstorageat-eth","https://docs.nodereal.io/reference/eth-getcode-eth","https://docs.nodereal.io/reference/event-logs","https://docs.nodereal.io/reference/eth-getfilterlogs-eth","https://docs.nodereal.io/reference/eth-getlogs-eth","https://docs.nodereal.io/reference/eth-uninstallfilter-eth","https://docs.nodereal.io/reference/eth-newblockfilter-eth","https://docs.nodereal.io/reference/eth-newpendingtransactionfilter-eth","https://docs.nodereal.io/reference/eth-getfilterchanges-eth","https://docs.nodereal.io/reference/eth-newfilter-eth","https://docs.nodereal.io/reference/chain-information","https://docs.nodereal.io/reference/eth-chainid-eth","https://docs.nodereal.io/reference/web3-clientversion-eth","https://docs.nodereal.io/reference/net-listening-eth","https://docs.nodereal.io/reference/net-version-eth","https://docs.nodereal.io/reference/uncle-blocks","https://docs.nodereal.io/reference/eth-getunclecountbyblockhash-eth","https://docs.nodereal.io/reference/eth-getunclecountbyblocknumber-eth","https://docs.nodereal.io/reference/eth-getunclebyblocknumberandindex-eth","https://docs.nodereal.io/reference/eth-getunclebyblockhashandindex-eth","https://docs.nodereal.io/reference/gas","https://docs.nodereal.io/reference/eth-estimategas-eth","https://docs.nodereal.io/reference/eth-gasprice-eth","https://docs.nodereal.io/reference/evm","https://docs.nodereal.io/reference/eth-sendrawtransaction-eth","https://docs.nodereal.io/reference/eth-call-eth","https://docs.nodereal.io/reference/blocks-1","https://docs.nodereal.io/reference/eth-blocknumber-eth","https://docs.nodereal.io/reference/eth-getblockbynumber-eth-old","https://docs.nodereal.io/reference/eth-getblockbynumber-eth","https://docs.nodereal.io/reference/eth-getblocktransactioncountbyhash-eth","https://docs.nodereal.io/reference/eth-getblocktransactioncountbynumber-eth","https://docs.nodereal.io/reference/eth-getblockbyhash-eth","https://docs.nodereal.io/reference/transaction","https://docs.nodereal.io/reference/eth-gettransactioncount-eth","https://docs.nodereal.io/reference/eth-gettransactionbyblockhashandindex-eth","https://docs.nodereal.io/reference/eth-gettransactionbyhash-eth","https://docs.nodereal.io/reference/eth-gettransactionbyblocknumberandindex-eth","https://docs.nodereal.io/reference/eth-gettransactionreceipt-eth","https://docs.nodereal.io/reference/websockets","https://docs.nodereal.io/reference/eth_subscribe-eth","https://docs.nodereal.io/reference/eth_unsubscribe-eth","https://docs.nodereal.io/reference/uniswap-graphql-api","https://docs.nodereal.io/reference/pancakeswap-graphql-api","https://docs.nodereal.io/reference/pancakeswap-graphql-api-v3","https://docs.nodereal.io/reference/fungible-tokens-api","https://docs.nodereal.io/reference/nr_gettokenbalance20","https://docs.nodereal.io/reference/nr_gettokencount","https://docs.nodereal.io/reference/nr_gettokenholdercount","https://docs.nodereal.io/reference/nr_gettokenholders","https://docs.nodereal.io/reference/nr_gettokenholdingcount","https://docs.nodereal.io/reference/nr_gettokenholdings","https://docs.nodereal.io/reference/nr_gettokenmeta","https://docs.nodereal.io/reference/nr_gettotalsupply20","https://docs.nodereal.io/reference/nr_historytokenholdersend","https://docs.nodereal.io/reference/nr_gethistorytokenholder","https://docs.nodereal.io/reference/nft-tokens-api","https://docs.nodereal.io/reference/nr_getnftcollectionholdercount","https://docs.nodereal.io/reference/nr_getnftcollectionholders","https://docs.nodereal.io/reference/nr_getnftholdercount","https://docs.nodereal.io/reference/nr_getnftholders","https://docs.nodereal.io/reference/nr_getnftholderswithbalance","https://docs.nodereal.io/reference/nr_getnftholdingcount","https://docs.nodereal.io/reference/nr_getnftholdings","https://docs.nodereal.io/reference/nr_getnftinventory","https://docs.nodereal.io/reference/nr_getnftmeta","https://docs.nodereal.io/reference/nr_getnfttokencount","https://docs.nodereal.io/reference/nr_getnfttokens","https://docs.nodereal.io/reference/nr_getnfttokenowners","https://docs.nodereal.io/reference/nr_getsummedsupply1155","https://docs.nodereal.io/reference/nr_gettokenbalance1155","https://docs.nodereal.io/reference/nr_gettokenbalance721","https://docs.nodereal.io/reference/nr_gettokenmeta-1","https://docs.nodereal.io/reference/nr_gettotalsupply1155","https://docs.nodereal.io/reference/nr_gettotalsupply721","https://docs.nodereal.io/reference/platform-api","https://docs.nodereal.io/reference/nr_health","https://docs.nodereal.io/reference/transaction-pool-api","https://docs.nodereal.io/reference/txpool_content","https://docs.nodereal.io/reference/txpool_inspect","https://docs.nodereal.io/reference/txpool_status","https://docs.nodereal.io/reference/transaction-receipts-api","https://docs.nodereal.io/reference/nr_getassettransfers","https://docs.nodereal.io/reference/nr_getassettransferscount","https://docs.nodereal.io/reference/nr_getcontractcreationtransaction","https://docs.nodereal.io/reference/nr_gettransactiondetail","https://docs.nodereal.io/reference/nr_gettransactionbyaddress","https://docs.nodereal.io/reference/nr_gettransactionbyaddresscount","https://docs.nodereal.io/reference/nr_gettransactionreceiptsbyblockhash","https://docs.nodereal.io/reference/nr_gettransactionreceiptsbyblocknumber","https://docs.nodereal.io/reference/nr_gettransferbytokenid","https://docs.nodereal.io/reference/debug-api","https://docs.nodereal.io/reference/debug-traceblockbyhash","https://docs.nodereal.io/reference/debug-traceblockbynumber","https://docs.nodereal.io/reference/debug-tracetransaction","https://docs.nodereal.io/reference/debug-tracecall","https://docs.nodereal.io/reference/eth_getdiffaccountswithscope","https://docs.nodereal.io/reference/eth_getdiffaccounts","https://docs.nodereal.io/reference/debug-pro-api","https://docs.nodereal.io/reference/debug_jstraceblockbyhash","https://docs.nodereal.io/reference/debug_jstraceblockbynumber","https://docs.nodereal.io/reference/debug_jstracecall","https://docs.nodereal.io/reference/debug_jstracetransaction","https://docs.nodereal.io/reference/trace_block","https://docs.nodereal.io/reference/trace_call","https://docs.nodereal.io/reference/trace_get","https://docs.nodereal.io/reference/trace_filter","https://docs.nodereal.io/reference/trace_transaction","https://docs.nodereal.io/reference/trace_replaytransaction","https://docs.nodereal.io/reference/trace_replayblocktransactions","https://docs.nodereal.io/reference/getcucunsumption","https://docs.nodereal.io/reference/cu-detail","https://docs.nodereal.io/reference/account-information-2","https://docs.nodereal.io/reference/eth-getstorageat-polygon","https://docs.nodereal.io/reference/post_-apikey","https://docs.nodereal.io/reference/eth-getbalance-polygon","https://docs.nodereal.io/reference/eth-getcode-polygon","https://docs.nodereal.io/reference/blocks-2","https://docs.nodereal.io/reference/eth-getblockbyhash-polygon","https://docs.nodereal.io/reference/eth-getblocktransactioncountbyhash-polygon","https://docs.nodereal.io/reference/eth-getblocktransactioncountbynumber-polygon","https://docs.nodereal.io/reference/eth-blocknumber-polygon","https://docs.nodereal.io/reference/chain-information-2","https://docs.nodereal.io/reference/eth-chainid-polygon","https://docs.nodereal.io/reference/bor-getauthor-polygon","https://docs.nodereal.io/reference/net-version-optimism","https://docs.nodereal.io/reference/web3-clientversion-polygon","https://docs.nodereal.io/reference/net-listening-optimism","https://docs.nodereal.io/reference/bor-getcurrentproposer-polygon","https://docs.nodereal.io/reference/bor-getcurrentvalidators-polygon","https://docs.nodereal.io/reference/bor-getroothash-polygon","https://docs.nodereal.io/reference/evm-2","https://docs.nodereal.io/reference/eth-sendrawtransaction-polygon","https://docs.nodereal.io/reference/eth-call-polygon","https://docs.nodereal.io/reference/gas-2","https://docs.nodereal.io/reference/eth-estimategas-polygon","https://docs.nodereal.io/reference/eth-gasprice-polygon","https://docs.nodereal.io/reference/event-logs-2","https://docs.nodereal.io/reference/eth-getfilterchanges-polygon","https://docs.nodereal.io/reference/eth-getfilterlogs-polygon","https://docs.nodereal.io/reference/eth-newpendingtransactionfilter-polygon","https://docs.nodereal.io/reference/eth-newfilter-polygon","https://docs.nodereal.io/reference/eth-uninstallfilter-optimism","https://docs.nodereal.io/reference/eth-newblockfilter-polygon","https://docs.nodereal.io/reference/eth-getlogs-polygon","https://docs.nodereal.io/reference/transactions-1","https://docs.nodereal.io/reference/eth-gettransactionbyblockhashandindex-polygon","https://docs.nodereal.io/reference/eth-gettransactionbyhash-polygon","https://docs.nodereal.io/reference/eth-gettransactionbyblocknumberandindex-polygon","https://docs.nodereal.io/reference/eth-gettransactioncount-polygon","https://docs.nodereal.io/reference/eth-gettransactionreceipt-polygon","https://docs.nodereal.io/reference/eth-gettransactionreceiptsbyblock-polygon","https://docs.nodereal.io/reference/uncle-blocks-2","https://docs.nodereal.io/reference/eth-getunclebyblockhashandindex-polygon","https://docs.nodereal.io/reference/eth-getunclebyblocknumberandindex-polygon","https://docs.nodereal.io/reference/eth-getunclecountbyblockhash-polygon","https://docs.nodereal.io/reference/eth-getunclecountbyblocknumber-polygon","https://docs.nodereal.io/reference/websockets-2","https://docs.nodereal.io/reference/eth_subscribe-3","https://docs.nodereal.io/reference/eth_unsubscribe-2","https://docs.nodereal.io/reference/account-information-3","https://docs.nodereal.io/reference/eth-getstorageat-optimism","https://docs.nodereal.io/reference/eth-accounts-optimism","https://docs.nodereal.io/reference/eth-getbalance-optimism","https://docs.nodereal.io/reference/eth-getcode-optimism","https://docs.nodereal.io/reference/blocks-4","https://docs.nodereal.io/reference/eth-getblockbyhash-optimism","https://docs.nodereal.io/reference/eth-getblockbynumber-optimism","https://docs.nodereal.io/reference/eth-getblocktransactioncountbyhash-optimism","https://docs.nodereal.io/reference/eth-blocknumber-optimism","https://docs.nodereal.io/reference/eth-getblocktransactioncountbynumber-optimism","https://docs.nodereal.io/reference/chain-information-3","https://docs.nodereal.io/reference/eth-chainid-optimism","https://docs.nodereal.io/reference/net-listening-optimism-1","https://docs.nodereal.io/reference/web3-sha3-optimism","https://docs.nodereal.io/reference/web3-clientversion-optimism","https://docs.nodereal.io/reference/eth-syncing-optimism","https://docs.nodereal.io/reference/net-version-optimism-1","https://docs.nodereal.io/reference/evm-3","https://docs.nodereal.io/reference/eth-sendrawtransaction-optimism","https://docs.nodereal.io/reference/eth-call-optimism","https://docs.nodereal.io/reference/gas-3","https://docs.nodereal.io/reference/eth-estimategas-optimism","https://docs.nodereal.io/reference/eth-gasprice-optimism","https://docs.nodereal.io/reference/event-logs-3","https://docs.nodereal.io/reference/eth-getfilterchanges-optimism","https://docs.nodereal.io/reference/eth-getlogs-optimism","https://docs.nodereal.io/reference/eth-newpendingtransactionfilter-optimism","https://docs.nodereal.io/reference/eth-uninstallfilter-optimism-1","https://docs.nodereal.io/reference/eth-getfilterlogs-optimism","https://docs.nodereal.io/reference/eth-newblockfilter-optimism","https://docs.nodereal.io/reference/eth-newfilter-optimism","https://docs.nodereal.io/reference/transactions-2","https://docs.nodereal.io/reference/eth-gettransactionbyblockhashandindex-optimism","https://docs.nodereal.io/reference/eth-gettransactionbyblocknumberandindex-optimism","https://docs.nodereal.io/reference/eth-gettransactioncount-optimism","https://docs.nodereal.io/reference/eth-gettransactionbyhash-optimism","https://docs.nodereal.io/reference/eth-gettransactionreceipt-optimism","https://docs.nodereal.io/reference/uncle-blocks-3","https://docs.nodereal.io/reference/eth-getunclebyblockhashandindex-optimism","https://docs.nodereal.io/reference/eth-getunclebyblocknumberandindex-optimism","https://docs.nodereal.io/reference/eth-getunclecountbyblockhash-optimism","https://docs.nodereal.io/reference/eth-getunclecountbyblocknumber-optimism","https://docs.nodereal.io/reference/websockets-3","https://docs.nodereal.io/reference/eth_subscribe-4","https://docs.nodereal.io/reference/eth_unsubscribe-3","https://docs.nodereal.io/reference/beacon-1","https://docs.nodereal.io/reference/getgenesis-1","https://docs.nodereal.io/reference/getstateroot-1","https://docs.nodereal.io/reference/getstatefork-1","https://docs.nodereal.io/reference/getstatefinalitycheckpoints-1","https://docs.nodereal.io/reference/getstatevalidators-1","https://docs.nodereal.io/reference/getstatevalidator-1","https://docs.nodereal.io/reference/getstatevalidatorbalances-1","https://docs.nodereal.io/reference/getepochcommittees-1","https://docs.nodereal.io/reference/getepochsynccommittees-1","https://docs.nodereal.io/reference/getblockheaders-1","https://docs.nodereal.io/reference/getblockheader-1","https://docs.nodereal.io/reference/publishblock-1","https://docs.nodereal.io/reference/publishblindedblock-1","https://docs.nodereal.io/reference/getblock-1","https://docs.nodereal.io/reference/getblockv2-1","https://docs.nodereal.io/reference/getblockroot-1","https://docs.nodereal.io/reference/getblockattestations-1","https://docs.nodereal.io/reference/getpoolattestations-1","https://docs.nodereal.io/reference/submitpoolattestations-1","https://docs.nodereal.io/reference/getpoolattesterslashings-1","https://docs.nodereal.io/reference/submitpoolattesterslashings-1","https://docs.nodereal.io/reference/getpoolproposerslashings-1","https://docs.nodereal.io/reference/submitpoolproposerslashings-1","https://docs.nodereal.io/reference/submitpoolsynccommitteesignatures-1","https://docs.nodereal.io/reference/getpoolvoluntaryexits-1","https://docs.nodereal.io/reference/submitpoolvoluntaryexit-1","https://docs.nodereal.io/reference/validatorrequiredapi-1","https://docs.nodereal.io/reference/getattesterduties","https://docs.nodereal.io/reference/getproposerduties","https://docs.nodereal.io/reference/getsynccommitteeduties","https://docs.nodereal.io/reference/produceblock","https://docs.nodereal.io/reference/produceblockv2","https://docs.nodereal.io/reference/produceblindedblock","https://docs.nodereal.io/reference/produceattestationdata","https://docs.nodereal.io/reference/getaggregatedattestation","https://docs.nodereal.io/reference/publishaggregateandproofs","https://docs.nodereal.io/reference/preparebeaconcommitteesubnet","https://docs.nodereal.io/reference/preparesynccommitteesubnets","https://docs.nodereal.io/reference/producesynccommitteecontribution","https://docs.nodereal.io/reference/publishcontributionandproofs","https://docs.nodereal.io/reference/preparebeaconproposer","https://docs.nodereal.io/reference/debug-1","https://docs.nodereal.io/reference/getstate-1","https://docs.nodereal.io/reference/getstatev2-1","https://docs.nodereal.io/reference/getdebugchainheads-1","https://docs.nodereal.io/reference/getdebugchainheadsv2-1","https://docs.nodereal.io/reference/node-1","https://docs.nodereal.io/reference/getnetworkidentity","https://docs.nodereal.io/reference/getpeers","https://docs.nodereal.io/reference/getpeer","https://docs.nodereal.io/reference/getpeercount","https://docs.nodereal.io/reference/getnodeversion","https://docs.nodereal.io/reference/getsyncingstatus","https://docs.nodereal.io/reference/gethealth","https://docs.nodereal.io/reference/config-1","https://docs.nodereal.io/reference/getforkschedule","https://docs.nodereal.io/reference/getspec","https://docs.nodereal.io/reference/getdepositcontract","https://docs.nodereal.io/reference/validator-1","https://docs.nodereal.io/reference/registervalidator","https://docs.nodereal.io/reference/events-2","https://docs.nodereal.io/reference/eventstream","https://docs.nodereal.io/reference/get-started-aptos","https://docs.nodereal.io/reference/accounts","https://docs.nodereal.io/reference/get_account","https://docs.nodereal.io/reference/get_account_resources","https://docs.nodereal.io/reference/get_account_modules","https://docs.nodereal.io/reference/get_account_resource","https://docs.nodereal.io/reference/get_account_module","https://docs.nodereal.io/reference/general","https://docs.nodereal.io/reference/spec","https://docs.nodereal.io/reference/healthy","https://docs.nodereal.io/reference/get_ledger_info","https://docs.nodereal.io/reference/blocks","https://docs.nodereal.io/reference/get_block_by_height","https://docs.nodereal.io/reference/get_block_by_version","https://docs.nodereal.io/reference/events","https://docs.nodereal.io/reference/get_events_by_event_key","https://docs.nodereal.io/reference/get_events_by_creation_number","https://docs.nodereal.io/reference/get_events_by_event_handle","https://docs.nodereal.io/reference/tables","https://docs.nodereal.io/reference/get_table_item","https://docs.nodereal.io/reference/transactions","https://docs.nodereal.io/reference/get_transactions","https://docs.nodereal.io/reference/submit_transaction","https://docs.nodereal.io/reference/get_transaction_by_hash","https://docs.nodereal.io/reference/get_transaction_by_version","https://docs.nodereal.io/reference/get_account_transactions","https://docs.nodereal.io/reference/submit_batch_transactions","https://docs.nodereal.io/reference/simulate_transaction","https://docs.nodereal.io/reference/encode_submission","https://docs.nodereal.io/reference/estimate_gas_price","https://docs.nodereal.io/reference/nftscan-api","https://docs.nodereal.io/reference/get-nfts-by-account","https://docs.nodereal.io/reference/get-all-nfts-by-account","https://docs.nodereal.io/reference/get-minted-nfts-by-account","https://docs.nodereal.io/reference/get-nfts-by-contract","https://docs.nodereal.io/reference/get-single-nft","https://docs.nodereal.io/reference/get-multiple-nfts","https://docs.nodereal.io/reference/search-nfts","https://docs.nodereal.io/reference/get-nfts-by-attributes","https://docs.nodereal.io/reference/get-all-multi-chain-nfts-by-account","https://docs.nodereal.io/reference/get-transactions-by-account","https://docs.nodereal.io/reference/get-transactions-by-contract","https://docs.nodereal.io/reference/get-transactions-by-nft","https://docs.nodereal.io/reference/search-transactions","https://docs.nodereal.io/reference/get-transactions-by-to-address","https://docs.nodereal.io/reference/get-transactions-by-hash","https://docs.nodereal.io/reference/get-an-nft-collection","https://docs.nodereal.io/reference/search-nft-collections","https://docs.nodereal.io/reference/get-nft-collections-by-account","https://docs.nodereal.io/reference/get-nft-collections-by-ranking","https://docs.nodereal.io/reference/trade-ranking","https://docs.nodereal.io/reference/mint-ranking","https://docs.nodereal.io/reference/mint-amount","https://docs.nodereal.io/reference/traders-ranking","https://docs.nodereal.io/reference/gas-ranking","https://docs.nodereal.io/reference/collection-ranking","https://docs.nodereal.io/reference/marketplace-ranking","https://docs.nodereal.io/reference/market-cap-ranking","https://docs.nodereal.io/reference/collection-statistics","https://docs.nodereal.io/reference/collection-trade-distribution","https://docs.nodereal.io/reference/collection-trending-statistics","https://docs.nodereal.io/reference/blue-chip","https://docs.nodereal.io/reference/account-overview","https://docs.nodereal.io/reference/account-holding-distribution","https://docs.nodereal.io/reference/collection-overview","https://docs.nodereal.io/reference/refresh-nft-metadata","https://docs.nodereal.io/reference/refresh-nft-metadata-by-contract","https://docs.nodereal.io/reference/get-latest-block-number","https://docs.nodereal.io/reference/get-nft-amount-by-account","https://docs.nodereal.io/reference/get-nft-owners-by-contract","https://docs.nodereal.io/reference/get-owners-by-an-nft","https://docs.nodereal.io/reference/covalent-api","https://docs.nodereal.io/reference/balances_v2","https://docs.nodereal.io/reference/transactions-4","https://docs.nodereal.io/reference/arbitrum-nova","https://docs.nodereal.io/reference/eth_blocknumber","https://docs.nodereal.io/reference/eth_call","https://docs.nodereal.io/reference/eth_chainid","https://docs.nodereal.io/reference/eth_estimategas","https://docs.nodereal.io/reference/eth_gasprice","https://docs.nodereal.io/reference/eth_getbalance","https://docs.nodereal.io/reference/eth_getblockbyhash","https://docs.nodereal.io/reference/eth_getblockbynumber","https://docs.nodereal.io/reference/eth_getblocktransactioncountbyhash","https://docs.nodereal.io/reference/eth_getblocktransactioncountbynumber","https://docs.nodereal.io/reference/eth_getcode","https://docs.nodereal.io/reference/eth_getfilterchanges","https://docs.nodereal.io/reference/eth_getfilterlogs","https://docs.nodereal.io/reference/eth_getlogs","https://docs.nodereal.io/reference/eth_getstorageat","https://docs.nodereal.io/reference/eth_gettransactionbyblockhashandindex","https://docs.nodereal.io/reference/eth_gettransactionbyblocknumberandindex","https://docs.nodereal.io/reference/eth_gettransactionbyhash","https://docs.nodereal.io/reference/eth_gettransactioncount-1","https://docs.nodereal.io/reference/eth_gettransactionreceipt","https://docs.nodereal.io/reference/eth_getunclecountbyblockhash","https://docs.nodereal.io/reference/eth_getunclecountbyblocknumber","https://docs.nodereal.io/reference/eth_newblockfilter","https://docs.nodereal.io/reference/eth_newfilter","https://docs.nodereal.io/reference/eth_newpendingtransactionfilter","https://docs.nodereal.io/reference/eth_sendrawtransaction","https://docs.nodereal.io/reference/eth_syncing","https://docs.nodereal.io/reference/net_version","https://docs.nodereal.io/reference/web3_clientversion","https://docs.nodereal.io/reference/avalanche-c-chain-avax","https://docs.nodereal.io/reference/avaxgetatomictx","https://docs.nodereal.io/reference/avaxgetutxos","https://docs.nodereal.io/reference/avaxissuetx","https://docs.nodereal.io/reference/avaxgetatomictxstatus","https://docs.nodereal.io/reference/eth_basefee","https://docs.nodereal.io/reference/eth_blocknumber-1","https://docs.nodereal.io/reference/eth_call-1","https://docs.nodereal.io/reference/eth_chainid-1","https://docs.nodereal.io/reference/eth_estimategas-1","https://docs.nodereal.io/reference/eth_gasprice-1","https://docs.nodereal.io/reference/eth_getassetbalance","https://docs.nodereal.io/reference/eth_getbalance-1","https://docs.nodereal.io/reference/eth_getblockbyhash-1","https://docs.nodereal.io/reference/eth_getblockbynumber-1","https://docs.nodereal.io/reference/eth_getblocktransactioncountbyhash-1","https://docs.nodereal.io/reference/eth_getblocktransactioncountbynumber-1","https://docs.nodereal.io/reference/eth_getcode-1","https://docs.nodereal.io/reference/eth_getlogs-1","https://docs.nodereal.io/reference/eth_getstorageat-1","https://docs.nodereal.io/reference/eth_gettransactionbyblockhashandindex-1","https://docs.nodereal.io/reference/eth_gettransactionbyblocknumberandindex-1","https://docs.nodereal.io/reference/eth_gettransactionbyhash-1","https://docs.nodereal.io/reference/eth_gettransactioncount-2","https://docs.nodereal.io/reference/eth_gettransactionreceipt-1","https://docs.nodereal.io/reference/eth_getunclebyblockhashandindex","https://docs.nodereal.io/reference/eth_getunclebyblocknumberandindex","https://docs.nodereal.io/reference/eth_getunclecountbyblockhash-1","https://docs.nodereal.io/reference/eth_getunclecountbyblocknumber-1","https://docs.nodereal.io/reference/eth_maxpriorityfeepergas","https://docs.nodereal.io/reference/eth_sendrawtransaction-1","https://docs.nodereal.io/reference/eth_syncing-1","https://docs.nodereal.io/reference/txpool_content-1","https://docs.nodereal.io/reference/txpool_inspect-1","https://docs.nodereal.io/reference/txpool_status-1","https://docs.nodereal.io/reference/net_version-1","https://docs.nodereal.io/reference/net_peercount","https://docs.nodereal.io/reference/web3_clientversion-1","https://docs.nodereal.io/reference/web3_sha3","https://docs.nodereal.io/reference/debug_traceblockbyhash-1","https://docs.nodereal.io/reference/debug_traceblockbynumber-1","https://docs.nodereal.io/reference/debug_tracecall-1","https://docs.nodereal.io/reference/debug_tracetransaction-1","https://docs.nodereal.io/reference/solana-rpc","https://docs.nodereal.io/reference/getaccountinfo","https://docs.nodereal.io/reference/getbalance","https://docs.nodereal.io/reference/getblock","https://docs.nodereal.io/reference/getblockcommitment","https://docs.nodereal.io/reference/getblockheight","https://docs.nodereal.io/reference/getblockproduction","https://docs.nodereal.io/reference/getblocks","https://docs.nodereal.io/reference/getblockswithlimit","https://docs.nodereal.io/reference/getblocktime","https://docs.nodereal.io/reference/getclusternodes","https://docs.nodereal.io/reference/getepochinfo","https://docs.nodereal.io/reference/getepochschedule","https://docs.nodereal.io/reference/getfeeformessage","https://docs.nodereal.io/reference/getfirstavailableblock","https://docs.nodereal.io/reference/getgenesishash","https://docs.nodereal.io/reference/gethealth-1","https://docs.nodereal.io/reference/gethighestsnapshotslot","https://docs.nodereal.io/reference/getidentity","https://docs.nodereal.io/reference/getinflationgovernor","https://docs.nodereal.io/reference/getinflationrate","https://docs.nodereal.io/reference/getinflationreward","https://docs.nodereal.io/reference/getlatestblockhash","https://docs.nodereal.io/reference/getleaderschedule","https://docs.nodereal.io/reference/getmaxretransmitslot","https://docs.nodereal.io/reference/getmaxshredinsertslot","https://docs.nodereal.io/reference/getminimumbalanceforrentexemption","https://docs.nodereal.io/reference/getmultipleaccounts","https://docs.nodereal.io/reference/getprogramaccounts","https://docs.nodereal.io/reference/getrecentperformancesamples","https://docs.nodereal.io/reference/getsignaturesforaddress","https://docs.nodereal.io/reference/getsignaturestatuses","https://docs.nodereal.io/reference/getslot","https://docs.nodereal.io/reference/getslotleader","https://docs.nodereal.io/reference/getslotleaders","https://docs.nodereal.io/reference/getstakeactivation","https://docs.nodereal.io/reference/getstakeminimumdelegation","https://docs.nodereal.io/reference/gettokenaccountbalance","https://docs.nodereal.io/reference/gettokenaccountsbyowner","https://docs.nodereal.io/reference/gettokensupply","https://docs.nodereal.io/reference/gettransaction","https://docs.nodereal.io/reference/gettransactioncount","https://docs.nodereal.io/reference/getversion","https://docs.nodereal.io/reference/getvoteaccounts","https://docs.nodereal.io/reference/isblockhashvalid","https://docs.nodereal.io/reference/minimumledgerslot","https://docs.nodereal.io/reference/requestairdrop","https://docs.nodereal.io/reference/sendtransaction","https://docs.nodereal.io/reference/simulatetransaction","https://docs.nodereal.io/reference/arbitrum-nitro","https://docs.nodereal.io/reference/eth_blocknumber-2","https://docs.nodereal.io/reference/eth_call-2","https://docs.nodereal.io/reference/eth_chainid-2","https://docs.nodereal.io/reference/eth_estimategas-2","https://docs.nodereal.io/reference/eth_gasprice-2","https://docs.nodereal.io/reference/eth_getbalance-2","https://docs.nodereal.io/reference/eth_getblockbyhash-2","https://docs.nodereal.io/reference/eth_getblockbynumber-2","https://docs.nodereal.io/reference/eth_getblocktransactioncountbyhash-2","https://docs.nodereal.io/reference/eth_getblocktransactioncountbynumber-2","https://docs.nodereal.io/reference/eth_getcode-2","https://docs.nodereal.io/reference/eth_getfilterchanges-1","https://docs.nodereal.io/reference/eth_getfilterlogs-1","https://docs.nodereal.io/reference/eth_getlogs-2","https://docs.nodereal.io/reference/eth_getstorageat-2","https://docs.nodereal.io/reference/eth_gettransactionbyblockhashandindex-2","https://docs.nodereal.io/reference/eth_gettransactionbyblocknumberandindex-2","https://docs.nodereal.io/reference/eth_gettransactionbyhash-2","https://docs.nodereal.io/reference/eth_gettransactioncount","https://docs.nodereal.io/reference/eth_gettransactionreceipt-2","https://docs.nodereal.io/reference/eth_getunclecountbyblockhash-2","https://docs.nodereal.io/reference/eth_getunclecountbyblocknumber-2","https://docs.nodereal.io/reference/eth_newblockfilter-1","https://docs.nodereal.io/reference/eth_newfilter-1","https://docs.nodereal.io/reference/eth_newpendingtransactionfilter-1","https://docs.nodereal.io/reference/eth_sendrawtransaction-2","https://docs.nodereal.io/reference/eth_syncing-2","https://docs.nodereal.io/reference/net_version-2"]

for index, link in enumerate(link_list):
    filename = f"{names[index]}.html"
    download_html(link, filename)